# Generated by Django 3.2.9 on 2021-12-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211204_1637'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
