# Generated by Django 3.2.9 on 2021-12-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20211206_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='is_ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordered',
            new_name='is_ordered',
        ),
    ]
