# Generated by Django 3.2.9 on 2021-11-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211120_1833'),
        ('accounts', '0004_rename_status_staff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='services.category'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active status'),
        ),
    ]
