# Generated by Django 3.2.9 on 2021-11-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
