# Generated by Django 3.2.9 on 2021-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211201_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
