# Generated by Django 3.2.9 on 2021-12-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Category Name'),
        ),
    ]
