# Generated by Django 3.2.9 on 2021-11-30 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211120_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='service',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_category', to='services.category'),
        ),
    ]
