# Generated by Django 3.2.9 on 2021-11-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211120_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='status',
            new_name='is_active',
        ),
    ]
