# Generated by Django 3.2.9 on 2021-12-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_staff_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(max_length=255),
        ),
    ]
