# Generated by Django 3.2.9 on 2021-12-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211120_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(choices=[('Abdullahpur', 'Abdullahpur'), ('Agargaon', 'Agargaon'), ('Badda', 'Badda'), ('Banani', 'Banani'), ('Banasree', 'Banasree'), ('Baridhara', 'Baridhara'), ('Bashundhara', 'Bashundhara'), ('Bawnia', 'Bawnia'), ('Beraid', 'Beraid'), ('Cantonment area', 'Cantonment area'), ('Dakshinkhan', 'Dakshinkhan'), ('Dania', 'Dania'), ('Demra', 'Demra'), ('Dhanmondi', 'Dhanmondi'), ('Farmgate', 'Farmgate'), ('Gabtali', 'Gabtali'), ('Gulshan', 'Gulshan'), ('Hazaribagh', 'Hazaribagh'), ('Islampur', 'Islampur'), ('Jurain', 'Jurain'), ('Kafrul', 'Kafrul'), ('Kamalapur', 'Kamalapur'), ('Kamrangirchar', 'Kamrangirchar'), ('Kazipara', 'Kazipara'), ('Khilgaon', 'Khilgaon'), ('Khilkhet', 'Khilkhet'), ('Kotwali', 'Kotwali'), ('Lalbagh', 'Lalbagh'), ('Matuail', 'Matuail'), ('Mirpur', 'Mirpur'), ('Mohakhali', 'Mohakhali'), ('Mohammadpur', 'Mohammadpur'), ('Motijheel', 'Motijheel'), ('Nimtoli', 'Nimtoli'), ('Pallabi', 'Pallabi'), ('Paltan', 'Paltan'), ('Ramna', 'Ramna'), ('Rampura', 'Rampura'), ('Sabujbagh', 'Sabujbagh'), ('Sadarghat', 'Sadarghat'), ('Satarkul', 'Satarkul'), ('Shahbagh', 'Shahbagh'), ('Sher-e-Bangla Nagar', 'Sher-e-Bangla Nagar'), ('Shyampur', 'Shyampur'), ('Sutrapur', 'Sutrapur'), ('Tejgaon', 'Tejgaon'), ('Uttara', 'Uttara'), ('Uttarkhan', 'Uttarkhan'), ('Vatara', 'Vatara'), ('Wari', 'Wari')], max_length=50),
        ),
    ]
