# Generated by Django 3.2.9 on 2021-12-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211203_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(editable=False, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(editable=False, verbose_name='Delivery Time'),
        ),
    ]
